"""initial schema

Revision ID: 042714b2ac99
Revises: 
Create Date: 2026-05-31 18:53:02.615996

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '042714b2ac99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
