"""add soft delete deleted_at

Revision ID: 16c7b08313ee
Revises: 042714b2ac99
Create Date: 2026-05-31 19:24:19.488468

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '16c7b08313ee'
down_revision: Union[str, None] = '042714b2ac99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_events_id'), table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_index(op.f('ix_resume_queue_id'), table_name='resume_queue')
    op.drop_table('resume_queue')
    op.drop_index(op.f('ix_claude_sessions_id'), table_name='claude_sessions')
    op.drop_index(op.f('ix_claude_sessions_session_id'), table_name='claude_sessions')
    op.drop_table('claude_sessions')
    op.add_column('milestones', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('milestones', 'deleted_at')
    op.create_table('claude_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('project_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('exit_reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), nullable=True),
    sa.Column('turns', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claude_sessions_session_id'), 'claude_sessions', ['session_id'], unique=1)
    op.create_index(op.f('ix_claude_sessions_id'), 'claude_sessions', ['id'], unique=False)
    op.create_table('resume_queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('project_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('checkpoint', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('queued_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resumed_at', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_queue_id'), 'resume_queue', ['id'], unique=False)
    op.create_table('rate_limit_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('occurred_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reset_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_events_id'), 'rate_limit_events', ['id'], unique=False)
    # ### end Alembic commands ###
