"""add priority to tasks

Revision ID: 17cde024dd63
Revises: 3d190f320c0a
Create Date: 2026-06-01 12:41:34.790205

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '17cde024dd63'
down_revision: Union[str, None] = '3d190f320c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('high', 'medium', 'low', name='taskpriority'), nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
