"""add window_earliest to code usage

Revision ID: 3d190f320c0a
Revises: fb75326b97cb
Create Date: 2026-06-01 00:22:36.078009

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3d190f320c0a'
down_revision: Union[str, None] = 'fb75326b97cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_usage_reports', sa.Column('window_earliest', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_usage_reports', 'window_earliest')
    # ### end Alembic commands ###
