"""add current_model to code usage

Revision ID: 806867173ed3
Revises: 17cde024dd63
Create Date: 2026-06-01 13:00:09.539718

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '806867173ed3'
down_revision: Union[str, None] = '17cde024dd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_usage_reports', sa.Column('current_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_usage_reports', 'current_model')
    # ### end Alembic commands ###
