"""add line_users and rate limit notification flags

Revision ID: b6f3565850dd
Revises: d5b07afb9484
Create Date: 2026-05-31 23:06:47.689470

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b6f3565850dd'
down_revision: Union[str, None] = 'd5b07afb9484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_users_id'), 'line_users', ['id'], unique=False)
    op.create_index(op.f('ix_line_users_user_id'), 'line_users', ['user_id'], unique=True)
    op.add_column('rate_limit_events', sa.Column('notified', sa.Boolean(), nullable=True))
    op.add_column('rate_limit_events', sa.Column('resolved_notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_limit_events', 'resolved_notified')
    op.drop_column('rate_limit_events', 'notified')
    op.drop_index(op.f('ix_line_users_user_id'), table_name='line_users')
    op.drop_index(op.f('ix_line_users_id'), table_name='line_users')
    op.drop_table('line_users')
    # ### end Alembic commands ###
