"""restore claude usage tables

Revision ID: d5b07afb9484
Revises: 16c7b08313ee
Create Date: 2026-05-31 19:24:47.760931

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd5b07afb9484'
down_revision: Union[str, None] = '16c7b08313ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claude_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claude_sessions_id'), 'claude_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_claude_sessions_session_id'), 'claude_sessions', ['session_id'], unique=True)
    op.create_table('rate_limit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_events_id'), 'rate_limit_events', ['id'], unique=False)
    op.create_table('resume_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_queue_id'), 'resume_queue', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_queue_id'), table_name='resume_queue')
    op.drop_table('resume_queue')
    op.drop_index(op.f('ix_rate_limit_events_id'), table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_index(op.f('ix_claude_sessions_session_id'), table_name='claude_sessions')
    op.drop_index(op.f('ix_claude_sessions_id'), table_name='claude_sessions')
    op.drop_table('claude_sessions')
    # ### end Alembic commands ###
