"""add code_usage_reports table

Revision ID: fb75326b97cb
Revises: ec180bf5aaa9
Create Date: 2026-06-01 00:16:18.739981

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fb75326b97cb'
down_revision: Union[str, None] = 'ec180bf5aaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_usage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_5h_input', sa.Integer(), nullable=True),
    sa.Column('window_5h_output', sa.Integer(), nullable=True),
    sa.Column('window_5h_cache_read', sa.Integer(), nullable=True),
    sa.Column('window_5h_cache_write', sa.Integer(), nullable=True),
    sa.Column('window_5h_messages', sa.Integer(), nullable=True),
    sa.Column('today_input', sa.Integer(), nullable=True),
    sa.Column('today_output', sa.Integer(), nullable=True),
    sa.Column('today_messages', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_usage_reports_id'), 'code_usage_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_usage_reports_id'), table_name='code_usage_reports')
    op.drop_table('code_usage_reports')
    # ### end Alembic commands ###
